server:
  port: 8088
mysql:
  user:
    name: zlb123
    passwd: test123
logging:
  config: classpath:logback-spring.xml
#  打印sql
  level:
    cn.zlb.dao: info
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://10.57.31.161:3306/risk_science_qa?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: test#2019

    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters，stat:监控统计、slf4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

mybatis:
  mapperLocations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml
